drop table if exists person_books;
drop table if exists APP_Book;
drop table if exists APP_USER;
create table APP_Book (
       id bigint GENERATED by default as identity ,
       NAME varchar(255) not null,
       AUTHOR varchar(255) not null,
       isbn varchar(255) not null,
       STATUS boolean
);

create table APP_USER (
       id  bigint GENERATED by default as identity,
       NAME varchar(255) not null,
       AGE int not null,
       ADDRESS varchar(255) not null,
       SEX varchar(100) not null
);       
       
       create table person_books (
      id bigint GENERATED by default as identity,
      user_id long not null,
      book_id long not null,
      CONSTRAINT pb_fk_user_id FOREIGN KEY (user_id) REFERENCES APP_USER (id),
      constraint pb_fk_book_id FOREIGN KEY (book_id) REFERENCES APP_Book (id),
      CONSTRAINT UNIQUE_BOOK_ID unique (book_id)
);
